version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: userExpress
      ME_CONFIG_BASICAUTH_PASSWORD: passExpress
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: userMongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: passMongo
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: userMongo
      MONGO_INITDB_ROOT_PASSWORD: passMongo
    ports:
      - "27017:27017"
    volumes:
      - /home/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
